* TODO 27 备份和自动保存

备份文件和自动保存文件是 Emacs 试图保护用户免受崩溃或用户自己错误的后果的两种方法。自动保存保留当前编辑会话中较早的文本；  备份文件保留当前会话之前的文件内容。

** TODO 27.1 备份文件

备份文件是您正在编辑的文件的旧内容的副本。Emacs 会在您第一次将缓冲区保存到其访问的文件中时创建一个备份文件。因此，通常，备份文件包含当前编辑会话之前的文件内容。备份文件的内容一旦存在通常保持不变。

通常通过将访问的文件重命名为新名称来进行备份。或者，您可以指定应通过复制访问的文件来制作备份文件。这种选择对于具有多个名称的文件会有所不同；  它还可以影响编辑后的文件是由原始所有者拥有还是由编辑它的用户拥有。

默认情况下，Emacs 为每个编辑的文件创建一个备份文件。您也可以请求编号备份；  然后每个新的备份文件都有一个新名称。当您不再需要旧编号备份时，您可以删除它们，或者 Emacs 可以自动删除它们。

出于性能考虑，操作系统可能不会立即将备份文件的内容写入辅助存储，或者可能会将备份数据与原始数据混为一谈，直到稍后修改其中一个或另一个。请参阅文件和辅助存储。

*** TODO 27.1.1 制作备份文件

#+begin_src emacs-lisp
  Function: backup-buffer ¶
#+end_src

    如果合适，此函数会备份当前缓冲区访问的文件。它在第一次保存缓冲区之前由 save-buffer 调用。

    如果通过重命名进行备份，则返回值是格式为 (modes extra-alist backupname) 的 cons 单元格，其中模式是原始文件的模式位，由 file-modes 返回（请参阅测试可访问性），extra -alist 是描述原始文件扩展属性的列表，由 file-extended-attributes 返回（请参阅扩展文件属性），backupname 是备份的名称。

    在所有其他情况下（即，如果通过复制进行备份或未进行备份），此函数返回 nil。

#+begin_src emacs-lisp
  Variable: buffer-backed-up ¶
#+end_src

    此缓冲区局部变量表示此缓冲区的文件是否已因此缓冲区而备份。如果它是非零，则备份文件已被写入。否则，下次保存文件时应备份文件（如果启用了备份）。这是一个永久的本地；  kill-all-local-variables 不会改变它。

#+begin_src emacs-lisp
  User Option: make-backup-files ¶
#+end_src

    该变量决定是否制作备份文件。如果它不是 nil，那么 Emacs 会在第一次保存每个文件时创建一个备份——前提是 backup-inhibited 是 nil（见下文）。

    以下示例显示了如何仅在 Rmail 缓冲区而不是其他地方更改 make-backup-files 变量。将它设置为 nil 会阻止 Emacs 备份这些文件，这可能会节省磁盘空间。（您可以将此代码放在您的初始化文件中。）
    #+begin_src emacs-lisp
      (add-hook 'rmail-mode-hook
		(lambda () (setq-local make-backup-files nil)))
    #+end_src

#+begin_src emacs-lisp
  Variable: backup-enable-predicate ¶
#+end_src

    这个变量的值是一个函数，在某些情况下被调用来决定一个文件是否应该有备份文件。该函数接收一个参数，一个要考虑的绝对文件名。如果函数返回 nil，则禁用该文件的备份。否则，本节中的其他变量说明是否以及如何进行备份。

    默认值为 normal-backup-enable-predicate，它检查临时文件目录和小临时文件目录中的文件。

#+begin_src emacs-lisp
  Variable: backup-inhibited ¶
#+end_src

    如果此变量不为零，则禁止备份。它记录了对访问的文件名进行备份启用谓词测试的结果。它也可以被其他机制一致地使用，这些机制根据访问的文件来禁止备份。例如，VC 将此变量设置为非零，以防止对使用版本控制系统管理的文件进行备份。

    这是一个永久的局部，所以改变主模式不会失去它的价值。主要模式不应该设置这个变量——它们应该设置 make-backup-files。

#+begin_src emacs-lisp
  User Option: backup-directory-alist ¶
#+end_src

    此变量的值是文件名模式和备份目录的列表。每个元素看起来像
    #+begin_src emacs-lisp
      (regexp . directory)
    #+end_src
    名称与正则表达式匹配的文件的备份将在目录中进行。目录可以是相对的或绝对的。如果是绝对的，那么所有匹配的文件都备份到同一个目录下，这个目录下的文件名就是备份文件的全名，所有的目录分隔符都改成'!'  以防止冲突。如果您的文件系统截断生成的名称，这将无法正常工作。

    对于所有备份都进入一个目录的常见情况，alist 应包含一个与相应目录配对的单个元素 ~。~ 。

    如果此变量为 nil（默认值），或者无法匹配文件名，则在原始文件的目录中进行备份。

    在没有长名称的 MS-DOS 文件系统上，这个变量总是被忽略。

#+begin_src emacs-lisp
  User Option: make-backup-file-name-function ¶
#+end_src

    该变量的值是用于制作备份文件名的函数。函数 make-backup-file-name 调用它。请参阅命名备份文件。

    这可能是缓冲区本地来为特定文件做一些特殊的事情。如果您更改它，您可能还需要更改 backup-file-name-p 和 file-name-sans-versions。

*** TODO 27.1.2 重命名备份还是复制备份？

Emacs 可以通过两种方式制作备份文件：

    Emacs 可以重命名原始文件，使其成为备份文件，然后将正在保存的缓冲区写入新文件。在此过程之后，原始文件的任何其他名称（即硬链接）现在都指向备份文件。新文件归进行编辑的用户所有，其组是用户在该目录中写入的新文件的默认组。
    Emacs 可以将原始文件复制到备份文件中，然后用新的内容覆盖原始文件。在此过程之后，原始文件的任何其他名称（即硬链接）继续引用文件的当前（更新）版本。文件的所有者和组将保持不变。

第一种方法，重命名，是默认的。

变量 backup-by-copying，如果非 nil，表示使用第二种方法，即复制原始文件并用新的缓冲区内容覆盖它。变量 file-precious-flag，如果非零，也有这种效果（作为其主要意义的副业）。请参阅保存缓冲区。

#+begin_src emacs-lisp
  User Option: backup-by-copying ¶
#+end_src

    如果这个变量不是 nil，Emacs 总是通过复制来备份文件。默认值为无。

以下三个变量，当非零时，会导致在某些特殊情况下使用第二种方法。它们对不属于特殊情况的文件的处理没有影响。

#+begin_src emacs-lisp
  User Option: backup-by-copying-when-linked ¶
#+end_src

    如果这个变量不为 nil，Emacs 会通过复制具有多个名称的文件（硬链接）来进行备份。默认值为无。

    仅当按复制备份为 nil 时，此变量才有意义，因为当该变量为非 nil 时始终使用复制。

#+begin_src emacs-lisp
  User Option: backup-by-copying-when-mismatch ¶
#+end_src

    如果此变量不为 nil（默认值），Emacs 会通过复制来进行备份，以防重命名会更改文件的所有者或组。

    当重命名不会改变文件的所有者或组时，该值无效；  也就是说，对于用户拥有的文件，并且其组与用户在其中创建的新文件的默认值匹配。

    仅当按复制备份为 nil 时，此变量才有意义，因为当该变量为非 nil 时始终使用复制。

#+begin_src emacs-lisp
  User Option: backup-by-copying-when-privileged-mismatch ¶
#+end_src

    此变量，如果非零，则指定与备份时复制时不匹配时相同的行为，但仅适用于某些用户 ID 和组 ID 值：即小于或等于某个数字的值。您将此变量设置为该数字。

    因此，如果您将 backup-by-copying-when-privileged-mismatch 设置为 0，则仅在必要时为超级用户和组 0 执行通过复制进行的备份，以防止更改文件的所有者。

    默认值为 200。

*** TODO 27.1.3 制作和删除编号备份文件

如果文件名为 foo，则其编号备份版本的名称为 foo.~v~，对于各种整数 v，如下所示：foo.~1~, foo.~2~, foo.~3~, ..., foo .~259~，依此类推。

#+begin_src emacs-lisp
  User Option: version-control ¶
#+end_src

    此变量控制是制作单个非编号备份文件还是制作多个编号备份。

#+begin_src emacs-lisp
  nil
#+end_src

	 如果访问的文件已经有编号备份，则进行编号备份；  否则，不要。这是默认设置。
#+begin_src emacs-lisp
  never
#+end_src

	 不要进行编号备份。
#+begin_src emacs-lisp
  anything else
#+end_src

	 进行编号备份。

使用编号备份最终会导致大量备份版本，然后必须将其删除。Emacs 可以自动执行此操作，也可以询问用户是否删除它们。

#+begin_src emacs-lisp
  User Option: kept-new-versions ¶
#+end_src

    此变量的值是进行新编号备份时要保留的最新版本数。新创建的备份包含在计数中。默认值为 2。

#+begin_src emacs-lisp
  User Option: kept-old-versions ¶
#+end_src

    此变量的值是创建新编号备份时要保留的最旧版本的数量。默认值为 2。

如果有编号为 1、2、3、5 和 7 的备份，并且这两个变量的值都为 2，则编号为 1 和 2 的备份保留为旧版本，编号为 5 和 7 的备份保留为新版本；  备份版本 3 是多余的。函数 find-backup-file-name（请参阅命名备份文件）负责确定要删除哪些备份版本，但不会自行删除它们。

#+begin_src emacs-lisp
  User Option: delete-old-versions ¶
#+end_src

    如果此变量为 t，则保存文件会静默删除多余的备份版本。如果为 nil，则表示在删除多余的备份之前要求确认。否则，它们根本不会被删除。

#+begin_src emacs-lisp
  User Option: dired-kept-versions ¶
#+end_src

    此变量指定在 Dired 命令中保留多少最新备份版本。（dired-clean-目录）。当您制作新的备份文件时，keep-new-versions 指定的内容相同。默认值为 2。

*** TODO 27.1.4 命名备份文件

记录本节中的功能主要是因为您可以通过重新定义备份文件来自定义它们的命名约定。如果你改变一个，你可能需要改变其余的。

#+begin_src emacs-lisp
  Function: backup-file-name-p filename ¶
#+end_src

    如果 filename 是备份文件的可能名称，则此函数返回非零值。它只是检查名称，而不是名称为 filename 的文件是否存在。

    #+begin_src emacs-lisp
      (backup-file-name-p "foo")
	   ⇒ nil

      (backup-file-name-p "foo~")
	   ⇒ 3
    #+end_src

    该函数的标准定义如下：
    #+begin_src emacs-lisp
      (defun backup-file-name-p (file)
	"Return non-nil if FILE is a backup file \
      name (numeric or not)..."
	(string-match "~\\'" file))
    #+end_src

    因此，如果文件名以 ~~~ 结尾，则该函数返回一个非零值。（我们使用反斜杠将文档字符串的第一行拆分为文本中的两行，但在字符串本身中只生成一行。）

    这个简单的表达式被放置在一个单独的函数中，以便于重新定义以进行定制。

#+begin_src emacs-lisp
  Function: make-backup-file-name filename ¶
#+end_src

    此函数返回一个字符串，该字符串是用于文件 filename 的非编号备份文件的名称。在 Unix 上，这只是附加了波浪号的文件名。

    在大多数操作系统上，该函数的标准定义如下：
    #+begin_src emacs-lisp
      (defun make-backup-file-name (file)
	"Create the non-numeric backup file name for FILE..."
	(concat file "~"))
    #+end_src

    您可以通过重新定义此函数来更改备份文件命名约定。以下示例重新定义 make-backup-file-name 以添加一个 '.'  除了附加波浪号：

    #+begin_src emacs-lisp
      (defun make-backup-file-name (filename)
	(expand-file-name
	  (concat "." (file-name-nondirectory filename) "~")
	  (file-name-directory filename)))


      (make-backup-file-name "backups.texi")
	   ⇒ ".backups.texi~"
    #+end_src


    Emacs 的某些部分，包括一些 Dired 命令，假定备份文件名以 ~~~ 结尾。如果您不遵循该约定，它不会导致严重的问题，但这些命令可能会产生不太理想的结果。

#+begin_src emacs-lisp
  Function: find-backup-file-name filename ¶
#+end_src

    此函数计算文件名的新备份文件的文件名。它还可能建议删除某些现有的备份文件。find-backup-file-name 返回一个列表，其 CAR 是新备份文件的名称，其 CDR 是建议删除的备份文件的列表。该值也可以为 nil，表示不进行备份。

    两个变量，保留旧版本和保留新版本，确定应保留哪些备份版本。此函数通过从值的 CDR 中排除这些版本来保留这些版本。请参阅制作和删除编号备份文件。

    在此示例中，该值表示 ~rms/foo.~5~ 是用于新备份文件的名称，而 ~rms/foo.~3~ 是调用者现在应该考虑删除的多余版本。

    #+begin_src emacs-lisp
      (find-backup-file-name "~rms/foo")
	   ⇒ ("~rms/foo.~5~" "~rms/foo.~3~")
    #+end_src
#+begin_src emacs-lisp
  Function: file-backup-file-names filename ¶
#+end_src

    此函数返回文件名的所有备份文件名的列表，如果没有，则返回 nil。文件按修改时间降序排列，最新的文件排在第一位。

#+begin_src emacs-lisp
  Function: file-newest-backup filename ¶
#+end_src

    此函数返回由 file-backup-file-names 返回的列表的第一个元素。

    一些文件比较命令使用此功能，以便它们可以自动将文件与其最近的备份进行比较。

** TODO 27.2 自动保存


Emacs 会定期保存您正在访问的所有文件；  这称为自动保存。如果系统崩溃，自动保存可防止您丢失超过有限数量的工作。默认情况下，每 300 次击键或大约 30 秒的空闲时间后会自动保存一次。有关用户自动保存的信息，请参阅 GNU Emacs 手册中的自动保存：防止灾难。这里我们描述用于实现自动保存的函数和控制它们的变量。

#+begin_src emacs-lisp
  Variable: buffer-auto-save-file-name ¶
#+end_src

    此缓冲区局部变量是用于自动保存当前缓冲区的文件的名称。如果缓冲区不应自动保存，则为 nil。

    #+begin_src emacs-lisp
      buffer-auto-save-file-name
	   ⇒ "/xcssun/users/rms/lewis/#backups.texi#"
    #+end_src

#+begin_src emacs-lisp
  Command: auto-save-mode arg ¶
#+end_src

    这是自动保存模式的模式命令，一种缓冲区本地次要模式。启用自动保存模式时，会在缓冲区中启用自动保存。调用约定与其他次要模式命令相同（请参阅编写次要模式的约定）。

    与大多数次要模式不同，没有自动保存模式变量。如果 buffer-auto-save-file-name 为非 nil 且 buffer-saved-size（见下文）非零，则启用自动保存模式。

#+begin_src emacs-lisp
  Variable: auto-save-file-name-transforms ¶
#+end_src

    此变量列出在生成自动保存文件名之前要应用于缓冲区文件名的转换。

    每个转换都是一个表单列表（正则表达式替换 [uniquify]）。regexp 是匹配文件名的正则表达式；  如果匹配，则使用replace-match 将匹配的部分替换为replacement。如果可选元素 uniquify 不为 nil，则自动保存文件名是通过将转换后的文件名的目录部分与缓冲区的文件名连接起来构建的，其中所有目录分隔符都更改为 ~！~   以防止冲突。（如果您的文件系统截断生成的名称，这将无法正常工作。）

    如果 uniquify 是 secure-hash-algorithms 的成员之一，Emacs 会通过将该安全哈希应用于缓冲区文件名来构造自动保存文件名的非目录部分。这避免了文件名过长的任何风险。

    列表中的所有转换都按照列出的顺序进行尝试。当一个变换应用时，它的结果是最终的；  没有尝试进一步的转换。

    默认值设置为将远程文件的自动保存文件放入临时目录（请参阅生成唯一文件名）。

    在没有长名称的 MS-DOS 文件系统上，这个变量总是被忽略。

#+begin_src emacs-lisp
  Function: auto-save-file-name-p filename ¶
#+end_src

    如果 filename 是一个可能是自动保存文件名称的字符串，则此函数返回一个非 nil 值。它假定自动保存文件的通常命名约定：以井号 ('#') 开头和结尾的名称是可能的自动保存文件名。参数文件名不应包含目录部分。
    #+begin_src emacs-lisp


      (make-auto-save-file-name)
	   ⇒ "/xcssun/users/rms/lewis/#backups.texi#"

      (auto-save-file-name-p "#backups.texi#")
	   ⇒ 0

      (auto-save-file-name-p "backups.texi")
	   ⇒ nil
    #+end_src

#+begin_src emacs-lisp
  Function: make-auto-save-file-name ¶
#+end_src

    此函数返回用于自动保存当前缓冲区的文件名。这只是带有哈希标记 ('#') 的文件名。此函数不查看变量 auto-save-visited-file-name（如下所述）；  此函数的调用者应首先检查该变量。

    #+begin_src emacs-lisp
      (make-auto-save-file-name)
	   ⇒ "/xcssun/users/rms/lewis/#backups.texi#"
    #+end_src

#+begin_src emacs-lisp
  User Option: auto-save-visited-file-name ¶
#+end_src

    如果这个变量不为 nil，Emacs 会在他们正在访问的文件中自动保存缓冲区。也就是说，自动保存在您正在编辑的同一文件中完成。通常，此变量为零，因此自动保存文件具有由 make-auto-save-file-name 创建的不同名称。

    当您更改此变量的值时，新值不会在现有缓冲区中生效，直到下次在其中重新启用自动保存模式。如果已启用自动保存模式，则自动保存将继续以相同的文件名进行，直到再次调用自动保存模式。

    请注意，将此变量设置为非零值不会改变自动保存与保存缓冲区不同的事实；  例如，当缓冲区被自动保存时，保存缓冲区中描述的钩子不会运行。

#+begin_src emacs-lisp
  Function: recent-auto-save-p ¶
#+end_src

    如果当前缓冲区自上次读入或保存后已自动保存，则此函数返回 t。

#+begin_src emacs-lisp
  Function: set-buffer-auto-saved ¶
#+end_src

    此函数将当前缓冲区标记为自动保存。在缓冲区文本再次更改之前，缓冲区不会再次自动保存。该函数返回零。

#+begin_src emacs-lisp
  User Option: auto-save-interval ¶
#+end_src

    此变量的值根据输入事件的数量指定自动保存的频率。每次读取这么多额外的输入事件时，Emacs 都会自动保存所有启用的缓冲区。将此设置为零会根据键入的字符数禁用自动保存。

#+begin_src emacs-lisp
  User Option: auto-save-timeout ¶
#+end_src

    此变量的值是应该导致自动保存的空闲时间秒数。每次用户暂停这么长时间，Emacs 都会自动保存所有启用该功能的缓冲区。（如果当前缓冲区很大，则指定的超时乘以一个随着大小增加而增加的因子；对于百万字节的缓冲区，该因子几乎是 4。）

    如果该值为 0 或 nil，则仅在 auto-save-interval 指定的一定数量的输入事件之后，才会由于空闲而不会执行自动保存。

#+begin_src emacs-lisp
  Variable: auto-save-hook ¶
#+end_src

    每当自动保存即将发生时，都会运行此正常挂钩。

#+begin_src emacs-lisp
  User Option: auto-save-default ¶
#+end_src

    如果此变量非零，则访问文件的缓冲区默认启用自动保存。否则，他们不会。

#+begin_src emacs-lisp
  Command: do-auto-save &optional no-message current-only ¶
#+end_src

    此功能自动保存所有需要自动保存的缓冲区。它保存启用了自动保存并且自上次自动保存以来已更改的所有缓冲区。

    如果任何缓冲区被自动保存，do-auto-save 通常会在自动保存进行时在回显区域显示一条消息 ~自动保存...~ 。但是，如果 no-message 不为零，则消息被禁止。

    如果 current-only 不为零，则仅自动保存当前缓冲区。

#+begin_src emacs-lisp
  Function: delete-auto-save-file-if-necessary &optional force ¶
#+end_src

    如果 delete-auto-save-files 不为零，则此函数删除当前缓冲区的自动保存文件。每次保存缓冲区时都会调用它。

    除非 force 为非 nil，否则此函数仅删除自上次真正保存以来由当前 Emacs 会话写入的文件。

#+begin_src emacs-lisp
  User Option: delete-auto-save-files ¶
#+end_src

    此变量由函数 delete-auto-save-file-if-necessary 使用。如果它不是 nil，Emacs 会在真正的保存完成时删除自动保存文件（在访问的文件中）。这可以节省磁盘空间并整理您的目录。

#+begin_src emacs-lisp
  Function: rename-auto-save-file ¶
#+end_src

    如果访问的文件名已更改，此函数会调整当前缓冲区的自动保存文件名。如果它是在当前 Emacs 会话中创建的，它还会重命名现有的自动保存文件。如果访问的文件名没有改变，这个函数什么也不做。

#+begin_src emacs-lisp
  Variable: buffer-saved-size ¶
#+end_src

    这个缓冲区局部变量的值是当前缓冲区的长度，当它最后一次读入、保存或自动保存时。这用于检测大小的显着减小，并作为响应关闭自动保存。

    如果为 -1，则表示由于大小大幅减少，此缓冲区中的自动保存暂时关闭。显式保存缓冲区会在此变量中存储一个正值，从而重新启用自动保存。关闭或打开自动保存模式也会更新此变量，因此会忘记大小的大幅减少。

    如果是 -2，这意味着这个缓冲区应该忽略缓冲区大小的变化；  特别是，它不应该因为缓冲区大小的变化而暂时关闭自动保存。

#+begin_src emacs-lisp
  Variable: auto-save-list-file-name ¶
#+end_src

    此变量（如果非零）指定一个文件，用于记录所有自动保存文件的名称。每次 Emacs 执行自动保存时，它都会为每个启用了自动保存的缓冲区将两行写入此文件。第一行给出访问文件的名称（如果缓冲区没有，则为空），第二行给出自动保存文件的名称。

    当 Emacs 正常退出时，它会删除这个文件；  如果 Emacs 崩溃，您可以在文件中查找所有可能包含丢失工作的自动保存文件。恢复会话命令使用此文件来查找它们。

    此文件的默认名称指定您的主目录并以 ~.saves-~ 开头。它还包含 Emacs 进程 ID 和主机名。

#+begin_src emacs-lisp
  User Option: auto-save-list-file-prefix ¶
#+end_src

    在 Emacs 读取您的 init 文件后，它会根据此前缀初始化 auto-save-list-file-name（如果您尚未将其设置为非 nil），并添加主机名和进程 ID。如果你在你的 init 文件中将它设置为 nil，那么 Emacs 不会初始化 auto-save-list-file-name。

** 27.3 还原

如果您对文件进行了大量更改，然后改变主意，您可以通过使用 revert-buffer 命令读取文件的先前版本来摆脱它们。请参阅 GNU Emacs 手册中的恢复缓冲区。

#+begin_src emacs-lisp
  Command: revert-buffer &optional ignore-auto noconfirm preserve-modes ¶
#+end_src

    此命令将缓冲区文本替换为磁盘上已访问文件的文本。此操作将撤消自访问或保存文件以来的所有更改。

    默认情况下，如果最新的自动保存文件比访问的文件更新，并且参数 ignore-auto 为 nil，revert-buffer 会询问用户是否使用该自动保存。当您以交互方式调用此命令时，如果没有数字前缀参数，则 ignore-auto 为 t；  因此，交互默认是不检查自动保存文件。

    通常，revert-buffer 在更改缓冲区之前会要求确认；  但如果参数 noconfirm 不为零，revert-buffer 不会要求确认。

    通常，此命令使用 normal-mode 重新初始化缓冲区的主要和次要模式。但如果 preserve-modes 不为零，则模式保持不变。

    还原尝试通过使用插入文件内容的替换功能来保留缓冲区中的标记位置。如果在还原操作之前缓冲区内容和文件内容相同，则还原会保留所有标记。如果它们不相同，则还原确实会更改缓冲区；  在这种情况下，它会在缓冲区的开头和结尾处保留未更改文本（如果有）中的标记。保留任何额外的标记都是有问题的。

    从非文件源恢复时，通常不会保留标记，但这取决于特定的恢复缓冲区功能实现。

#+begin_src emacs-lisp
  Variable: revert-buffer-in-progress-p ¶
#+end_src

    revert-buffer 在工作时将此变量绑定到非零值。

您可以通过设置本节其余部分中描述的变量来自定义 revert-buffer 的工作方式。

#+begin_src emacs-lisp
  User Option: revert-without-query ¶
#+end_src

    此变量包含应在不进行查询的情况下还原的文件列表。该值是一个正则表达式列表。如果访问的文件名与这些正则表达式之一匹配，并且文件在磁盘上已更改但缓冲区未修改，则 revert-buffer 会在不询问用户确认的情况下恢复文件。

一些主要模式通过为这些变量进行缓冲区本地绑定来自定义恢复缓冲区：

#+begin_src emacs-lisp
  Variable: revert-buffer-function ¶
#+end_src

    此变量的值是用于恢复此缓冲区的函数。它应该是一个带有两个可选参数的函数来完成恢复工作。两个可选参数，ignore-auto 和 noconfirm，是 revert-buffer 接收到的参数。

    在 Dired 模式等模式下，正在编辑的文本不包含文件的内容，但可以以其他方式重新生成，可以为该变量提供一个缓冲区本地值，该值是重新生成内容的特殊函数。

#+begin_src emacs-lisp
  Variable: revert-buffer-insert-file-contents-function ¶
#+end_src

    此变量的值指定在恢复此缓冲区时用于插入更新内容的函数。该函数接收两个参数：首先是要使用的文件名；  其次，如果用户要求读取自动保存文件，则为 t。

    模式更改此变量而不是 revert-buffer-function 的原因是避免重复或替换 revert-buffer 所做的其余部分：请求确认、清除撤消列表、确定正确的主要模式和运行挂钩下面列出。

#+begin_src emacs-lisp
  Variable: before-revert-hook ¶
#+end_src

    在插入修改的内容之前，这个普通的钩子由默认的 revert-buffer-function 运行。自定义的 revert-buffer-function 可能会也可能不会运行这个钩子。

#+begin_src emacs-lisp
  Variable: after-revert-hook ¶
#+end_src

    这个普通的钩子在插入修改的内容后由默认的 revert-buffer-function 运行。自定义的 revert-buffer-function 可能会也可能不会运行这个钩子。

Emacs 可以自动恢复缓冲区。默认情况下，它对访问文件的缓冲区执行此操作。下面介绍如何添加对自动恢复新类型缓冲区的支持。

首先，此类缓冲区必须定义合适的恢复缓冲区功能和缓冲区陈旧功能。

#+begin_src emacs-lisp
  Variable: buffer-stale-function ¶
#+end_src

    这个变量的值指定一个函数来调用来检查缓冲区是否需要恢复。默认值仅通过检查其修改时间来处理正在访问文件的缓冲区。不访问文件的缓冲区需要一个可选参数 noconfirm 的自定义函数。如果应该恢复缓冲区，该函数应该返回非零。调用此函数时，缓冲区是当前的。

    虽然此功能主要用于自动恢复，但它也可以用于其他目的。例如，如果未启用自动恢复，它可以用来警告用户缓冲区需要恢复。noconfirm 参数背后的想法是，如果要在不询问用户的情况下恢复缓冲区，则它应该是 t，如果函数只是用于警告用户缓冲区已过期，它应该是 nil。特别是，对于自动恢复的使用，noconfirm 是 t。如果该函数仅用于自动恢复，则可以忽略 noconfirm 参数。

    如果您只想每隔 auto-revert-interval 秒自动恢复（如缓冲区菜单），请使用：
    #+begin_src emacs-lisp
      (setq-local buffer-stale-function
	   (lambda (&optional noconfirm) 'fast))
    #+end_src

    在缓冲区的模式功能中。

    特殊的返回值 ~fast~ 告诉调用者是否需要恢复，但恢复缓冲区的速度很快。它还告诉 Auto Revert 不打印任何恢复消息，即使 auto-revert-verbose 不为零。这很重要，因为每隔 auto-revert-interval 秒获取恢复消息可能非常烦人。如果出于自动恢复以外的目的查询该函数，则此返回值提供的信息也可能很有用。

一旦缓冲区具有合适的恢复缓冲区功能和缓冲区陈旧功能，通常会存在几个问题。

缓冲区仅在标记为未修改时才会自动恢复。因此，当且仅当缓冲区包含可能因恢复而丢失的信息，或者有理由相信用户可能因自动恢复而感到不便时，您必须确保各种函数将缓冲区标记为已修改，因为他正在积极处理缓冲区。用户总是可以通过手动调整缓冲区的修改状态来覆盖它。为了支持这一点，在标记为未修改的缓冲区上调用 revert-buffer-function 应始终保持标记为未修改的缓冲区。

重要的是要确保该点不会由于自动恢复而不断跳跃。当然，如果缓冲区发生根本变化，移动点可能是不可避免的。

您应该确保 revert-buffer-function 不会打印不必要地重复 Auto Revert 自己的消息的消息，如果 auto-revert-verbose 为 t 则显示，并有效地覆盖 auto-revert-verbose 的 nil 值。因此，适应自动恢复模式通常涉及摆脱此类消息。这对于每隔 auto-revert-interval 秒自动恢复的缓冲区尤为重要。

如果新的自动恢复是 Emacs 的一部分，您应该在 global-auto-revert-non-file-buffers 的文档字符串中提及它。

同样，您应该在 Emacs 手册中记录添加的内容。
