* 附录 G 标准键盘映射
在本节中，我们列出了一些更通用的键盘映射。其中许多在 Emacs 首次启动时存在，但有些仅在访问相应功能时才加载。

除了这些，还有许多其他更专业的地图。特别是那些与主要和次要模式相关的。minibuffer 使用多个键映射（请参阅完成完成的 Minibuffer 命令）。有关键映射的更多详细信息，请参阅键映射。

#+begin_src emacs-lisp
  2C-mode-map
#+end_src

    前缀 Cx 6 的子命令的稀疏键映射。
    请参阅 GNU Emacs 手册中的两列编辑。
#+begin_src emacs-lisp
  abbrev-map ¶
#+end_src

    前缀 Cx a 的子命令的稀疏键映射。
    请参阅 GNU Emacs 手册中的定义缩写。
#+begin_src emacs-lisp
  button-buffer-map
#+end_src

    对包含缓冲区的缓冲区有用的稀疏键映射。
    您可能希望将其用作父键映射。请参阅按钮。
#+begin_src emacs-lisp
  button-map
#+end_src

    按钮使用的稀疏键盘映射。
#+begin_src emacs-lisp
  ctl-x-4-map
#+end_src

    前缀 Cx 4 的子命令的稀疏键映射。
#+begin_src emacs-lisp
  ctl-x-5-map
#+end_src

    前缀 Cx 5 的子命令的稀疏键映射。
#+begin_src emacs-lisp
  ctl-x-map
#+end_src

    Cx 命令的完整键盘映射。
#+begin_src emacs-lisp
  ctl-x-r-map ¶
#+end_src

    前缀 Cx r 的子命令的稀疏键映射。
    请参阅 GNU Emacs 手册中的寄存器。
#+begin_src emacs-lisp
  esc-map
#+end_src

    ESC（或 Meta）命令的完整键盘映射。
#+begin_src emacs-lisp
  function-key-map
#+end_src

    所有本地功能键映射 (qv) 实例的父键映射。
#+begin_src emacs-lisp
  global-map
#+end_src

    包含默认全局键绑定的完整键映射。
    模式不应修改全局地图。
#+begin_src emacs-lisp
  goto-map
#+end_src

    用于 Mg 前缀键的稀疏键映射。
#+begin_src emacs-lisp
  help-map
#+end_src

    帮助字符 Ch 之后的键的稀疏键映射。
    请参阅帮助功能。
#+begin_src emacs-lisp
  Helper-help-map
#+end_src

    帮助实用程序包使用的完整键盘映射。
    它在其值单元格和功能单元格中具有相同的键映射。
#+begin_src emacs-lisp
  input-decode-map
#+end_src

    用于翻译键盘和功能键的键盘映射。
    如果没有，则它包含一个空的稀疏键映射。请参阅用于翻译事件序列的键映射。
#+begin_src emacs-lisp
  key-translation-map
#+end_src

    用于翻译键的键映射。与 local-function-key-map 不同，这个覆盖了普通的键绑定。请参阅用于翻译事件序列的键映射。
#+begin_src emacs-lisp
  kmacro-keymap ¶
#+end_src

    遵循 Cx Ck 前缀搜索的键的稀疏键映射。
    请参阅 GNU Emacs 手册中的键盘宏。
#+begin_src emacs-lisp
  local-function-key-map
#+end_src

    用于将键序列转换为首选替代项的键映射。
    如果没有，则它包含一个空的稀疏键映射。请参阅用于翻译事件序列的键映射。
#+begin_src emacs-lisp
  menu-bar-file-menu ¶
#+end_src
#+begin_src emacs-lisp
  menu-bar-edit-menu
#+end_src
#+begin_src emacs-lisp
  menu-bar-options-menu
#+end_src
#+begin_src emacs-lisp
  global-buffers-menu-map
#+end_src
#+begin_src emacs-lisp
  menu-bar-tools-menu
#+end_src
#+begin_src emacs-lisp
  menu-bar-help-menu
#+end_src

    这些键映射在菜单栏中显示主要的顶级菜单。
    其中一些包含子菜单。例如，编辑菜单包含菜单栏搜索菜单等。请参阅菜单栏。
#+begin_src emacs-lisp
  minibuffer-inactive-mode-map
#+end_src

    小缓冲区不活动时使用的完整键盘映射。
    请参阅 GNU Emacs 手册中的 Minibuffer 中的编辑。
#+begin_src emacs-lisp
  mode-line-coding-system-map ¶
#+end_src
#+begin_src emacs-lisp
  mode-line-input-method-map
#+end_src
#+begin_src emacs-lisp
  mode-line-column-line-number-mode-map
#+end_src

    这些键映射控制模式行的各个区域。
    请参阅模式行格式。
#+begin_src emacs-lisp
  mode-specific-map
#+end_src

    抄送后字符的键盘映射。请注意，这是在全球地图中。此映射实际上不是特定于模式的：它的名称被选择为在 Ch b（显示绑定）中提供信息，它描述了 Cc 前缀键的主要用途。
#+begin_src emacs-lisp
  mouse-appearance-menu-map ¶
#+end_src

    用于 S-mouse-1 键的稀疏键映射。
#+begin_src emacs-lisp
  mule-keymap
#+end_src

    用于 Cx RET 前缀键的全局键映射。
#+begin_src emacs-lisp
  narrow-map ¶
#+end_src

    前缀 Cx n 的子命令的稀疏键映射。
#+begin_src emacs-lisp
  prog-mode-map
#+end_src

    Prog 模式使用的键盘映射。
    请参阅基本主要模式。
#+begin_src emacs-lisp
  query-replace-map
#+end_src
#+begin_src emacs-lisp
  multi-query-replace-map
#+end_src

    用于查询替换和相关命令中的响应的稀疏键映射；  也适用于 y-or-np 和 map-y-or-np。使用此映射的函数不支持前缀键；  他们一次查找一个事件。multi-query-replace-map 扩展 query-replace-map 以进行多缓冲区替换。请参阅查询替换映射。
#+begin_src emacs-lisp
  search-map
#+end_src

    为搜索相关命令提供全局绑定的稀疏键映射。
#+begin_src emacs-lisp
  special-mode-map
#+end_src

    特殊模式使用的键盘映射。
    请参阅基本主要模式。
#+begin_src emacs-lisp
  tab-prefix-map
#+end_src

    用于选项卡栏相关命令的 Cx t 前缀键的全局键映射。
    请参阅 GNU Emacs 手册中的选项卡栏。
#+begin_src emacs-lisp
  tab-bar-map
#+end_src

    定义选项卡栏内容的键映射。
    请参阅 GNU Emacs 手册中的选项卡栏。
#+begin_src emacs-lisp
  tool-bar-map
#+end_src

    定义工具栏内容的键盘映射。
    请参阅工具栏。
#+begin_src emacs-lisp
  universal-argument-map ¶
#+end_src

    处理 Cu 时使用的稀疏键映射。
    请参阅前缀命令参数。
#+begin_src emacs-lisp
  vc-prefix-map
#+end_src

    用于 Cx v 前缀键的全局键映射。
#+begin_src emacs-lisp
  x-alternatives-map ¶
#+end_src

    用于在图形框架下映射某些键的稀疏键映射。
    函数 x-setup-function-keys 使用它。
