* 附录 B GNU自由文档许可证
1.3 版，2008 年 11 月 3 日

版权所有 © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/

每个人都可以复制和分发逐字副本
本许可证文件的内容，但不允许更改。

0.  前言

    本许可证的目的是使手册、教科书或其他功能性和有用的文档在自由的意义上免费：确保每个人都有复制和重新分发它的有效自由，无论是否修改它，无论是商业性的还是非商业性的。其次，本许可证为作者和出版商保留了一种获得作品荣誉的方式，同时不被认为对他人所做的修改负责。

    本许可证是一种 ~copyleft~ ，这意味着该文件的衍生作品本身必须在同一意义上是免费的。它补充了 GNU 通用公共许可证，后者是专为自由软件设计的 copyleft 许可证。

    我们设计此许可证是为了将其用于自由软件的手册，因为自由软件需要免费文档：自由程序应附带提供与软件相同的自由的手册。但本许可不限于软件手册；它可以用于任何文本作品，无论主题如何，也无论它是否作为印刷书籍出版。我们建议将此许可主要用于以指导或参考为目的的作品。

1.  适用性和定义

    本许可适用于任何媒体中的任何手册或其他作品，其中包含版权所有者放置的通知，说明可以根据本许可的条款分发。这样的通知授予在全球范围内、免版税、期限不受限制的许可，以在此处所述的条件下使用该作品。下面的 ~文档~ 指任何此类手册或作品。任何公众成员都是被许可人，并被称为 ~您~ 。如果您以需要版权法许可的方式复制、修改或分发作品，则表示您接受许可。

    文件的 ~修改版本~ 是指包含文件或其一部分的任何作品，无论是逐字复制，还是经过修改和/或翻译成另一种语言。

     ~次要部分~ 是文件的命名附录或前文部分，专门处理文件的出版商或作者与文件的整体主题（或相关事项）的关系，不包含任何可能直接属于的内容在这个整体主题内。（因此，如果该文件部分是数学教科书，则中学部可能不会解释任何数学。）这种关系可能是与主题或相关问题的历史联系，或法律、商业、哲学、伦理或关于他们的政治立场。

     ~不变节~ 是某些次要节，其标题被指定为不变节的标题，在通知中说明该文档是根据本许可证发布的。如果一个部分不符合上述 Secondary 的定义，则不允许将其指定为 Invariant。文档可能包含零个不变部分。如果文档没有标识任何不变部分，则没有。

     ~封面文本~ 是在说明文档根据本许可发布的通知中作为封面文本或封底文本列出的某些简短文本段落。Front-Cover Text 最多 5 个单词，Back-Cover Text 最多 25 个单词。

    文档的 ~透明~ 副本是指机器可读的副本，以一种其规范可供公众使用的格式表示，适用于使用通用文本编辑器或（对于由像素组成的图像）​​通用油漆直接修改文档程序或（用于绘图）一些广泛可用的绘图编辑器，适合输入到文本格式器或自动翻译成适合输入到文本格式器的各种格式。以其他透明文件格式制作的副本，其标记或没有标记已被安排以阻止或阻止读者随后的修改，这不是透明的。如果用于任何大量文本，则图像格式不是透明的。不 ~透明~ 的副本称为 ~不透明~ 。

    透明副本的合适格式示例包括无标记的纯 ASCII、Texinfo 输入格式、LaTeX 输入格式、使用公开可用的 DTD 的 SGML 或 XML，以及为人工修改而设计的符合标准的简单 HTML、PostScript 或 PDF。透明图像格式的示例包括 PNG、XCF 和 JPG。不透明格式包括只能由专有文字处理器读取和编辑的专有格式，DTD 和/或处理工具通常不可用的 SGML 或 XML，以及由某些文字处理器生成的机器生成的 HTML、PostScript 或 PDF仅用于输出目的。

    对于印刷书籍， ~扉页~ 是指扉页本身，以及为清晰地保存本许可要求出现在扉页中的材料而需要的后续页面。对于没有任何标题页的格式的作品， ~标题页~ 是指靠近作品标题最突出外观的文本，位于正文开头之前。

     ~发布者~ 是指向公众分发文档副本的任何个人或实体。

     ~标题为 XYZ~ 的部分是指文档的命名子单元，其标题恰好是 XYZ 或在将 XYZ 翻译成另一种语言的文本后的括号中包含 XYZ。（这里 XYZ 代表下面提到的特定部分名称，例如 ~Acknowledgements~ 、 ~Dedicates~ 、 ~Endorsements~ 或 ~History~ 。）在您修改文档时 ~保留此类部分的标题~ 意味着它根据此定义，仍然是 ~标题为 XYZ~ 的部分。

    该文档可能在声明本许可适用于该文档的通知旁边包含保修免责声明。这些保修免责声明被视为通过引用包含在本许可中，但仅限于免责声明：这些保修免责声明可能具有的任何其他含义均无效，并且对本许可的含义没有影响。

2.  逐字复制

    您可以以商业或非商业方式在任何媒体中复制和分发文档，前提是本许可、版权声明和说明本许可适用于文档的许可声明在所有副本中复制，并且您不添加任何其他条件到本许可证的那些。您不得使用技术措施来阻止或控制对您制作或分发的副本的阅读或进一步复制。但是，您可以接受补偿以换取副本。如果您分发的副本数量足够多，您还必须遵守第 3 节中的条件。

    您也可以在上述相同条件下借出副本，并且可以公开展示副本。
3.  大量复制

    如果您发布文档的印刷副本（或通常具有印刷封面的媒体中的副本），编号超过 100，并且该文档的许可通知需要封面文本，您必须将副本附在封面中，清晰易读地载有所有这些封面文字：封面上的封面文字，封底上的封底文字。两份封面还必须清楚地表明您是这些副本的出版商。封面必须呈现完整的标题，并且标题的所有单词都同样突出和可见。此外，您可以在封面上添加其他材料。复制仅限于封面，只要保留文件的标题并满足这些条件，在其他方面都可以视为逐字复制。

    如果任一封面所需的文字过于冗长而无法清晰阅读，则应将列出的第一个（尽可能多的合理）放在实际封面上，然后将其余的继续放在相邻的页面上。

    如果您发布或分发文档编号超过 100 个的不透明副本，您必须在每个不透明副本中包含一个机器可读的透明副本，或者在每个不透明副本中或在每个不透明副本中声明一个计算机网络位置，通用网络从该位置-使用 public 可以使用公共标准网络协议下载文档的完整透明副本，无需添加材料。如果您使用后一种选择，则在开始大量分发不透明副本时，您必须采取合理谨慎的步骤，以确保此透明副本在您最后一次分发不透明副本后至少一年后仍可在指定位置访问。该版本的不透明副本（直接或通过您的代理或零售商）向公众公开。

    在重新分发任何大量副本之前，请但不要求您与文档的作者联系，以便他们有机会为您提供文档的更新版本。

4.  修改
    您可以根据上述第 2 节和第 3 节的条件复制和分发文档的修改版本，前提是您完全根据本许可发布修改版本，修改版本充当文档的角色，从而许可分发和修改修改后的版本给拥有它的副本的人。此外，您必须在修改版中执行以下操作：
    1. 在标题页（和封面，如果有的话）中使用与文档不同的标题，也不同于以前版本的标题（如果有的话，应该在文档的历史部分列出）。如果该版本的原始出版商允许，您可以使用与以前版本相同的标题。
    2. 在标题页上列出作为作者，负责修改版本中的修改的作者身份的一个或多个个人或实体，以及文档的至少五位主要作者（所有主要作者，如果它少于五），除非他们从这个要求中释放你。
    3. 在标题页上注明修改版本的发布者的名称，作为发布者。
    4. 保留文档的所有版权声明。
    5. 在其他版权声明旁边为您的修改添加适当的版权声明。
    6. 在版权声明之后立即包括一个许可声明，允许公众根据本许可的条款使用修改版，格式如下面的附录所示。
    7. 在该许可通知中保留文档许可通知中给出的不变部分和所需封面文本的完整列表。
    8. 包括本许可证的未更改副本。
    9. 保留标题为 ~历史~ 的部分，保留其标题，并在其中添加一个项目，至少说明标题页上给出的修改版本的标题、年份、新作者和出版商。如果文档中没有标题为 ~历史~ 的部分，请创建一个说明文档标题页上给出的文档的标题、年份、作者和出版商，然后添加一个描述修改版本的项目，如上句所述。
    10. 保留文档中给定的网络位置（如果有），以供公众访问文档的透明副本，同样保留文档中给定的先前版本所基于的网络位置。这些可以放在 ~历史~ 部分。您可以省略在文档本身之前至少四年出版的作品的网络位置，或者如果它所引用版本的原始出版商给予许可。
    11. 对于标题为 ~致谢~ 或 ~奉献~ 的任何部分，请保留该部分的标题，并在该部分中保留其中给出的每个贡献者致谢和/或奉献的所有内容和语气。
    12. 保留文档的所有不变部分，在其文本和标题中保持不变。章节编号或同等内容不被视为章节标题的一部分。
    13. 删除任何标题为 ~背书~ 的部分。这样的部分可能不包括在修改版本中。
    14. 不要将任何现有部分重新命名为 ~背书~ 或与任何不变部分的标题冲突。
    15. 保留任何保修免责声明。

    如果修改后的版本包括符合次要部分的新的前面部分或附录，并且不包含从文档中复制的材料，您可以选择将这些部分中的部分或全部指定为不变。为此，请将它们的标题添加到修改版许可声明中的不变部分列表中。这些标题必须与任何其他章节标题不同。

    您可以添加标题为 ~背书~ 的部分，前提是它只包含各方对您的修改版本的背书——例如，同行评审声明或文本已被组织批准为标准的权威定义。

    您可以在修改后的封面文本列表的末尾添加最多 5 个单词的段落作为封面文本，以及最多 25 个单词的段落作为封底文本。任何一个实体只能（或通过安排）添加一篇封面文字和一篇封底文字。如果文件已包含同一封面的封面文本，由您先前添加或由您代表的同一实体作出安排，您不得添加另一个；但您可以替换旧的，但要获得添加旧版本的前一个发布者的明确许可。

    文档的作者和发布者未通过本许可授权使用他们的姓名来宣传或主张或暗示对任何修改版本的认可。

5.  合并文件

    您可以根据上述第 4 节中为修改版本定义的条款将本文档与根据本许可发布的其他文档组合，前提是您在组合中包含所有未修改的原始文档的所有不变部分，并将它们全部列出作为您在其许可通知中的组合作品的不变部分，并且您保留其所有保修免责声明。

    合并后的作品只需包含一份本许可证，多个相同的不变部分可以用一个副本替换。如果有多个同名但内容不同的 Invariant Sections，则通过在其末尾添加该部分的原作者或出版商的名称（如果知道），使每个此类部分的标题唯一，或者添加一个唯一编号。对组合作品的许可通知中不变章节列表中的章节标题进行相同的调整。

    在组合中，您必须将各种原始文件中的任何一个名为 ~历史~ 的部分组合在一起，形成一个名为 ~历史~ 的部分；同样，将标题为 ~致谢~ 的任何部分和标题为 ~奉献~ 的任何部分结合起来。您必须删除所有标题为 ~背书~ 的部分。

6.  文件集

    您可以制作一个包含文档和根据本许可发布的其他文档的集合，并使用包含在集合中的单个副本替换各种文档中的本许可的各个副本，前提是您遵守本许可的规则在所有其他方面逐字复制每份文件。

    您可以从此类集合中提取单个文档，并根据本许可单独分发它，前提是您将本许可的副本插入到提取的文档中，并在所有其他方面遵守本许可，以逐字复制该文档。
7.  与独立工作的聚合

    如果汇编产生的版权不用于限制合法权利，则在存储或分发介质的卷中或之上的文档或其衍生文件与其他单独和独立的文档或作品的汇编称为 ~集合~ 超出个人作品允许范围的编辑用户。当文档包含在集合中时，本许可不适用于集合中的其他作品，这些作品本身不是文档的衍生作品。

    如果第 3 节的封面文本要求适用于文件的这些副本，则如果文件少于整个总数的一半，则文件的封面文本可以放置在将文件括在总数中的封面上，或者如果文件是电子形式，则电子版的封面。否则，它们必须出现在包含整个聚合体的印刷封面上。
8.  翻译

    翻译被认为是一种修改，因此您可以根据第 4 节的条款分发文档的翻译。用翻译替换不变节需要其版权所有者的特别许可，但您可以包括部分或全部不变节的翻译，除了这些不变部分的原始版本。您可以包含本许可的翻译版本、文档中的所有许可通知以及任何保修免责声明，前提是您还包含本许可的英文原版以及这些通知和免责声明的原始版本。如果本许可证的翻译版本与原始版本或通知或免责声明存在分歧，以原始版本为准。

    如果文档中的某个部分标题为 ~致谢~ 、 ~奉献~ 或 ~历史~ ，则保留其标题（第 1 部分）的要求（第 4 部分）通常需要更改实际标题。
9.  终止

    除非本许可明确规定，否则您不得复制、修改、再许可或分发文档。以其他方式复制、修改、再许可或分发它的任何尝试都是无效的，并将自动终止您在本许可下的权利。

    但是，如果您停止所有违反本许可的行为，则 (a) 临时恢复您从特定版权持有人处获得的许可，除非且直到版权持有人明确并最终终止您的许可，以及 (b) 如果版权持有人未终止许可，则永久恢复在停止后 60 天之前通过某种合理的方式通知您违规行为。

    此外，如果版权所有者以某种合理的方式通知您违规行为，您从特定版权所有者那里获得的许可将永久恢复，这是您第一次收到该版权所有者关于违反本许可（任何作品）的通知，并且您在收到通知后的 30 天内纠正违规行为。

    终止您在本节项下的权利不会终止根据本许可从您那里收到副本或权利的各方的许可。如果您的权利已被终止且未永久恢复，则收到部分或全部相同材料的副本并不赋予您任何使用它的权利。
10. 本许可的未来修订

    自由软件基金会可能会不时发布 GNU 自由文档许可证的新修订版本。此类新版本在精神上与当前版本相似，但可能在细节上有所不同，以解决新问题或关注点。请参阅 https://www.gnu.org/licenses/。

    许可证的每个版本都有一个可区分的版本号。如果文档指定本许可证的特定编号版本 ~或任何更高版本~ 适用于它，您可以选择遵循该指定版本或已发布的任何更高版本的条款和条件（不是作为草案）由自由软件基金会。如果文档未指定本许可证的版本号，您可以选择自由软件基金会曾经发布过的任何版本（而不是草稿）。如果文档指定代理可以决定可以使用本许可证的哪些未来版本，则该代理接受某个版本的公开声明永久授权您为文档选择该版本。
11. 重新许可

     ~大型多作者协作网站~ （或 ~MMC 网站~ ）是指发布受版权保护的作品并为任何人编辑这些作品提供显着设施的任何万维网服务器。任何人都可以编辑的公共 wiki 就是这种服务器的一个例子。网站中包含的 ~大规模多作者协作~ （或 ~MMC~ ）是指在 MMC 网站上发布的任何受版权保护的作品集。

     ~CC-BY-SA~ 是指由 Creative Commons Corporation 发布的 Creative Commons Attribution-Share Alike 3.0 许可证，该公司是一家主要营业地位于加利福尼亚州旧金山的非营利性公司，以及该许可证的未来 copyleft 版本由同一组织发布的许可证。

     ~合并~ 是指作为另一份文件的一部分全部或部分发布或重新发布一份文件。

    如果 MMC 根据本许可获得许可，并且如果所有作品首先根据本许可在本 MMC 以外的其他地方发布，随后全部或部分并入 MMC，则 MMC 是 ~有资格获得再许可的~ ，(1)封面文本或不变部分，以及 (2) 因此在 2008 年 11 月 1 日之前并入。

    MMC 站点的运营商可以在 2009 年 8 月 1 日之前的任何时间根据 CC-BY-SA 在同一站点上重新发布站点中包含的 MMC，前提是 MMC 有资格获得重新许可。

附录：如何将此许可证用于您的文档

要在您编写的文档中使用本许可，请在文档中包含许可的副本，并在标题页之后放置以下版权和许可声明：

#+begin_src emacs-lisp
  版权所有 (C) 年份您的姓名。
  授予复制、分发和/或修改本文档的权限
  根据 GNU 自由文档许可证 1.3 版的条款
  或自由软件基金会发布的任何更新版本；
  没有不变的部分，没有封面文本，也没有封底
  文本。许可证的副本包含在标题为 ``GNU
  免费文档许可证''。
#+end_src

如果您有固定部分、封面文本和封底文本，请将 ~with...Texts~ 替换。与此一致：

#+begin_src emacs-lisp
  Invariant Sections 列出了它们的标题，其中
  Front-Cover Texts 被列出，并且带有 Back-Cover Texts
  正在列表中。
#+end_src

如果您有没有封面文本的不变部分，或三者的其他组合，请合并这两个替代方案以适应情况。

如果您的文档包含程序代码的重要示例，我们建议在您选择的自由软件许可证（例如 GNU 通用公共许可证）下并行发布这些示例，以允许它们在自由软件中使用。
