#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: elegantpaper
#+OPTIONS: prop:t
#+OPTIONS: ^:nil

* TODO 附录 H 标准挂钩

以下是一些钩子变量的列表，这些变量让您可以在适当的情况下提供从 Emacs 中调用的函数。

 大多数这些变量的名称都以“-hook”结尾。  它们是普通的钩子，通过 run-hooks 运行。  这种钩子的值是一个函数列表；  这些函数在没有参数的情况下被调用，并且它们的值被完全忽略。  在这种钩子上放置新函数的推荐方法是调用 add-hook。  有关使用钩子的更多信息，请参阅钩子。

 名称以“-functions”结尾的变量通常是异常钩子（一些旧代码也可能使用已弃用的“-hooks”后缀）。  它们的值是函数列表，但这些函数以特殊方式调用：它们要么是传递的参数，要么以某种方式使用它们的返回值。  名称以“-function”结尾的变量具有单个函数作为它们的值。

 这不是一个详尽的列表，它只涵盖了更一般的钩子。  例如，每个主要模式都定义了一个名为“modename-mode-hook”的钩子。  主模式命令使用 run-mode-hooks 作为它执行的最后一件事来运行这个普通的钩子。  请参阅模式挂钩。  大多数次要模式也有模式挂钩。

 一项特殊功能允许您指定表达式以评估是否以及何时加载文件（请参阅加载挂钩）。  该功能不完全是一个钩子，但做了类似的工作。

 激活标记挂钩
 停用标记挂钩

     见标记。
 变更后功能
 变更前功能
 第一换钩

     请参阅更改挂钩。
 更改后主要模式挂钩
 主体钩子后更改主要模式

     请参阅模式挂钩。
 初始化后挂钩
 初始化前挂钩
 emacs 启动钩子
 窗口设置挂钩

     请参阅初始化文件。
 插入文件后函数
 写区域注释函数
 写区域后注释功能

     请参阅文件格式转换。
 后制作框架功能
 前制作框架挂钩
 服务器后制作框架挂钩

     请参阅创建框架。
 保存后挂钩
 保存前挂钩
 写内容函数
 写文件函数

     请参阅保存缓冲区。
 设置后字体挂钩¶

     框架字体更改后的挂钩运行。
 自动保存挂钩

     请参阅自动保存。
 before-hack-local-variables-hook
 hack-local-variables-hook

     请参阅文件局部变量。
 缓冲区访问字体化功能

     请参阅文本属性的延迟计算。
 缓冲区列表更新挂钩¶

     当缓冲区列表更改时挂钩运行（请参阅缓冲区列表）。
 缓冲退出函数¶

     调用以退出当前缓冲区的函数。
 更改主要模式挂钩

     请参阅创建和删除缓冲区本地绑定。
 comint-密码功能

     这个异常钩子允许派生模式在不提示用户的情况下为底层命令解释器提供密码。
 命令行功能

     请参阅命令行参数。
 延迟警告挂钩¶

     命令循环在 post-command-hook (qv) 后不久运行。
 钩子焦点¶
 焦点外挂

     请参阅输入焦点。
 删除帧函数
 删除帧后功能

     请参阅删除框架。
 删除终端功能

     请参阅多个终端。
 弹出框功能
 拆分窗口首选功能

     请参阅显示缓冲区的其他选项。
 回声区清除挂钩

     请参阅回声区域自定义。
 查找文件挂钩
 查找文件未找到功能

     请参阅访问文件的函数。
 font-lock-extend-after-change-region-function

     请参阅缓冲区更改后要字体化的区域。
 字体锁定扩展区域功能

     请参阅多行字体锁定结构。
 字体锁定字体缓冲功能
 字体锁定字体区域功能
 字体锁定标记块功能
 字体锁定取消字体缓冲功能
 字体锁定取消字体化区域功能

     请参阅其他字体锁定变量。
 字体化功能

     请参阅自动面分配。
 框架自动隐藏功能

     请参阅退出 Windows。
 退出窗口挂钩

     请参阅退出 Windows。
 杀死缓冲钩子
 杀死缓冲区查询功能

     请参阅杀死缓冲区。
 杀死 emacs 钩子
 杀死 emacs 查询功能

     请参阅杀死 Emacs。
 菜单栏更新挂钩

     请参阅菜单栏。
 minibuffer-setup-hook
 minibuffer-exit-hook

     请参阅 Minibuffer Miscellany。
 鼠标离开缓冲钩 ¶

     当用户在窗口中单击鼠标时挂钩运行。
 鼠标位置功能

     请参阅鼠标位置。
 前缀命令回声击键功能¶

     由前缀命令（例如 Cu）运行的异常钩子，它应该返回描述当前前缀状态的字符串。  例如，Cu 产生“Cu-”和“Cu 1 2 3-”。  每个钩子函数都在没有参数的情况下被调用，并且应该返回一个描述当前前缀状态的字符串，如果没有前缀状态，则返回 nil。  请参阅前缀命令参数。
 前缀命令保留状态挂钩¶

     当前缀命令需要通过将当前前缀命令状态传递给下一个命令来保留前缀时，挂钩运行。  例如，当用户键入 Cu 时，Cu 需要将状态传递给下一个命令 - 或者在 Cu 后面跟一个数字。
 预重显示功能

     在重新显示之前在每个窗口中运行钩子。  请参阅强制重新显示。
 命令后挂钩
 预命令挂钩

     请参阅命令循环概述。
 后 gc 挂钩

     请参阅垃圾收集。
 后自插入挂钩

     请参阅键盘映射和次要模式。
 挂勾
 暂停恢复挂钩
 挂起 tty 函数
 恢复 tty 函数

     请参阅暂停 Emacs。
 语法开始函数
 语法属性扩展区域函数
 语法属性函数
 字体锁定句法面函数

     请参阅语法字体锁定。  请参阅语法属性。
 临时缓冲区设置挂钩
 临时缓冲区显示功能
 临时缓冲区显示挂钩

     请参阅临时展示。
 tty 设置挂钩

     请参阅特定于终端的初始化。
 窗口配置更改挂钩
 窗口滚动功能
 窗口大小更改函数

     请参阅用于窗口滚动和更改的挂钩。
