#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: elegantpaper
#+OPTIONS: prop:t
#+OPTIONS: ^:nil

* 附录 H 标准挂钩
以下是一些钩子变量的列表，这些变量让您可以在适当的情况下提供从 Emacs 中调用的函数。

大多数这些变量的名称都以 ~-hook~ 结尾。它们是普通的钩子，通过 run-hooks 运行。这种钩子的值是一个函数列表；  这些函数在没有参数的情况下被调用，并且它们的值被完全忽略。在这种钩子上放置新函数的推荐方法是调用 add-hook。有关使用钩子的更多信息，请参阅钩子。

名称以 ~-functions~ 结尾的变量通常是异常钩子（一些旧代码也可能使用已弃用的 ~-hooks~ 后缀）。它们的值是函数列表，但这些函数以特殊方式调用：它们要么是传递的参数，要么以某种方式使用它们的返回值。名称以 ~-function~ 结尾的变量具有单个函数作为它们的值。

这不是一个详尽的列表，它只涵盖了更一般的钩子。例如，每个主要模式都定义了一个名为 ~modename-mode-hook~ 的钩子。主模式命令使用 run-mode-hooks 作为它执行的最后一件事来运行这个普通的钩子。请参阅模式挂钩。大多数次要模式也有模式挂钩。

一项特殊功能允许您指定表达式以评估是否以及何时加载文件（请参阅加载挂钩）。该功能不完全是一个钩子，但做了类似的工作。

#+begin_src emacs-lisp
  activate-mark-hook
#+end_src
#+begin_src emacs-lisp
  deactivate-mark-hook
#+end_src

    见标记。
#+begin_src emacs-lisp
  after-change-functions
#+end_src
#+begin_src emacs-lisp
  before-change-functions
#+end_src
#+begin_src emacs-lisp
  first-change-hook
#+end_src

    请参阅更改挂钩。
#+begin_src emacs-lisp
  after-change-major-mode-hook
#+end_src
#+begin_src emacs-lisp
  change-major-mode-after-body-hook
#+end_src

    请参阅模式挂钩。
#+begin_src emacs-lisp
  after-init-hook
#+end_src
#+begin_src emacs-lisp
  before-init-hook
#+end_src
#+begin_src emacs-lisp
  emacs-startup-hook
#+end_src
#+begin_src emacs-lisp
  window-setup-hook
#+end_src

    请参阅初始化文件。
#+begin_src emacs-lisp
  after-insert-file-functions
#+end_src
#+begin_src emacs-lisp
  write-region-annotate-functions
#+end_src
#+begin_src emacs-lisp
  write-region-post-annotation-function
#+end_src

    请参阅文件格式转换。
#+begin_src emacs-lisp
  after-make-frame-functions
#+end_src
#+begin_src emacs-lisp
  before-make-frame-hook
#+end_src
#+begin_src emacs-lisp
  server-after-make-frame-hook
#+end_src

    请参阅创建框架。
#+begin_src emacs-lisp
  after-save-hook
#+end_src
#+begin_src emacs-lisp
  before-save-hook
#+end_src
#+begin_src emacs-lisp
  write-contents-functions
#+end_src
#+begin_src emacs-lisp
  write-file-functions
#+end_src

    请参阅保存缓冲区。
#+begin_src emacs-lisp
  after-setting-font-hook ¶
#+end_src

    框架字体更改后的挂钩运行。
#+begin_src emacs-lisp
  auto-save-hook
#+end_src

    请参阅自动保存。
#+begin_src emacs-lisp
  before-hack-local-variables-hook
#+end_src
#+begin_src emacs-lisp
  hack-local-variables-hook
#+end_src

    请参阅文件局部变量。
#+begin_src emacs-lisp
  buffer-access-fontify-functions
#+end_src

    请参阅文本属性的延迟计算。
#+begin_src emacs-lisp
  buffer-list-update-hook ¶
#+end_src

    当缓冲区列表更改时挂钩运行（请参阅缓冲区列表）。
#+begin_src emacs-lisp
  buffer-quit-function ¶
#+end_src

    调用以退出当前缓冲区的函数。
#+begin_src emacs-lisp
  change-major-mode-hook
#+end_src

    请参阅创建和删除缓冲区本地绑定。
#+begin_src emacs-lisp
  comint-password-function
#+end_src

    这个异常钩子允许派生模式在不提示用户的情况下为底层命令解释器提供密码。
#+begin_src emacs-lisp
  command-line-functions
#+end_src

    请参阅命令行参数。
#+begin_src emacs-lisp
  delayed-warnings-hook ¶
#+end_src

    命令循环在 post-command-hook (qv) 后不久运行。
#+begin_src emacs-lisp
  focus-in-hook ¶
#+end_src
#+begin_src emacs-lisp
  focus-out-hook
#+end_src

    请参阅输入焦点。
#+begin_src emacs-lisp
  delete-frame-functions
#+end_src
#+begin_src emacs-lisp
  after-delete-frame-functions
#+end_src

    请参阅删除框架。
#+begin_src emacs-lisp
  delete-terminal-functions
#+end_src

    请参阅多个终端。
#+begin_src emacs-lisp
  pop-up-frame-function
#+end_src
#+begin_src emacs-lisp
  split-window-preferred-function
#+end_src

    请参阅显示缓冲区的其他选项。
#+begin_src emacs-lisp
  echo-area-clear-hook
#+end_src

    请参阅回声区域自定义。
#+begin_src emacs-lisp
  find-file-hook
#+end_src
#+begin_src emacs-lisp
  find-file-not-found-functions
#+end_src

    请参阅访问文件的函数。
#+begin_src emacs-lisp
  font-lock-extend-after-change-region-function
#+end_src

    请参阅缓冲区更改后要字体化的区域。
#+begin_src emacs-lisp
  font-lock-extend-region-functions
#+end_src

    请参阅多行字体锁定结构。
#+begin_src emacs-lisp
  font-lock-fontify-buffer-function
#+end_src
#+begin_src emacs-lisp
  font-lock-fontify-region-function
#+end_src
#+begin_src emacs-lisp
  font-lock-mark-block-function
#+end_src
#+begin_src emacs-lisp
  font-lock-unfontify-buffer-function
#+end_src
#+begin_src emacs-lisp
  font-lock-unfontify-region-function
#+end_src

    请参阅其他字体锁定变量。
#+begin_src emacs-lisp
  fontification-functions
#+end_src

    请参阅自动面分配。
#+begin_src emacs-lisp
  frame-auto-hide-function
#+end_src

    请参阅退出 Windows。
#+begin_src emacs-lisp
  quit-window-hook
#+end_src

    请参阅退出 Windows。
#+begin_src emacs-lisp
  kill-buffer-hook
#+end_src
#+begin_src emacs-lisp
  kill-buffer-query-functions
#+end_src

    请参阅杀死缓冲区。
#+begin_src emacs-lisp
  kill-emacs-hook
#+end_src
#+begin_src emacs-lisp
  kill-emacs-query-functions
#+end_src

    请参阅杀死 Emacs。
#+begin_src emacs-lisp
  menu-bar-update-hook
#+end_src

    请参阅菜单栏。
#+begin_src emacs-lisp
  minibuffer-setup-hook
#+end_src
#+begin_src emacs-lisp
  minibuffer-exit-hook
#+end_src

    请参阅 Minibuffer Miscellany。
#+begin_src emacs-lisp
  mouse-leave-buffer-hook ¶
#+end_src

    当用户在窗口中单击鼠标时挂钩运行。
#+begin_src emacs-lisp
  mouse-position-function
#+end_src

    请参阅鼠标位置。
#+begin_src emacs-lisp
  prefix-command-echo-keystrokes-functions ¶
#+end_src

    由前缀命令（例如 Cu）运行的异常钩子，它应该返回描述当前前缀状态的字符串。例如，Cu 产生 ~Cu-~ 和 ~Cu 1 2 3-~ 。每个钩子函数都在没有参数的情况下被调用，并且应该返回一个描述当前前缀状态的字符串，如果没有前缀状态，则返回 nil。请参阅前缀命令参数。
#+begin_src emacs-lisp
  prefix-command-preserve-state-hook ¶
#+end_src

    当前缀命令需要通过将当前前缀命令状态传递给下一个命令来保留前缀时，挂钩运行。例如，当用户键入 Cu 时，Cu 需要将状态传递给下一个命令 - 或者在 Cu 后面跟一个数字。
#+begin_src emacs-lisp
  pre-redisplay-functions
#+end_src

    在重新显示之前在每个窗口中运行钩子。请参阅强制重新显示。
#+begin_src emacs-lisp
  post-command-hook
#+end_src
#+begin_src emacs-lisp
  pre-command-hook
#+end_src

    请参阅命令循环概述。
#+begin_src emacs-lisp
  post-gc-hook
#+end_src

    请参阅垃圾收集。
#+begin_src emacs-lisp
  post-self-insert-hook
#+end_src

    请参阅键盘映射和次要模式。
#+begin_src emacs-lisp
  suspend-hook
#+end_src
#+begin_src emacs-lisp
  suspend-resume-hook
#+end_src
#+begin_src emacs-lisp
  suspend-tty-functions
#+end_src
#+begin_src emacs-lisp
  resume-tty-functions
#+end_src

    请参阅暂停 Emacs。
#+begin_src emacs-lisp
  syntax-begin-function
#+end_src
#+begin_src emacs-lisp
  syntax-propertize-extend-region-functions
#+end_src
#+begin_src emacs-lisp
  syntax-propertize-function
#+end_src
#+begin_src emacs-lisp
  font-lock-syntactic-face-function
#+end_src

    请参阅语法字体锁定。请参阅语法属性。
#+begin_src emacs-lisp
  temp-buffer-setup-hook
#+end_src
#+begin_src emacs-lisp
  temp-buffer-show-function
#+end_src
#+begin_src emacs-lisp
  temp-buffer-show-hook
#+end_src

    请参阅临时展示。
#+begin_src emacs-lisp
  tty-setup-hook
#+end_src

    请参阅特定于终端的初始化。
#+begin_src emacs-lisp
  window-configuration-change-hook
#+end_src
#+begin_src emacs-lisp
  window-scroll-functions
#+end_src
#+begin_src emacs-lisp
  window-size-change-functions
#+end_src

    请参阅用于窗口滚动和更改的挂钩。
